### ISSUE TITLE
The type initializer for 'Simple301.Core.RedirectRepository' threw an exception

### ISSUE THREAD

**Issue by tvanro** [wkallhof/Simple301#2]
One of our sites is using Simple301 and was down for 2 days displaying following error in the logs. 
When I restarted the site (with touching the web.config), the site was up and running again.

Any idea what the issue could be? 

>ERROR Umbraco.Core.UmbracoApplicationBase - An unhandled exception occurred
System.TypeInitializationException: The type initializer for 'Simple301.Core.RedirectRepository' threw an exception. ---> System.Data.SqlClient.SqlException: Connection Timeout Expired.  The timeout period elapsed during the post-login phase.  The connection could have timed out while waiting for server to complete the login process and respond; Or it could have timed out while attempting to create multiple active connections.  The duration spent while attempting to connect to this server was - [Pre-Login] initialization=0; handshake=5596; [Login] initialization=0; authentication=0; [Post-Login] complete=8995;  ---> System.ComponentModel.Win32Exception: The wait operation timed out
   --- End of inner exception stack trace ---
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at System.Data.SqlClient.SqlConnection.Open()
   at Umbraco.Core.Persistence.FaultHandling.RetryPolicy.<>c__DisplayClass1.<ExecuteAction>b__0()
   at Umbraco.Core.Persistence.FaultHandling.RetryPolicy.ExecuteAction[TResult](Func`1 func)
   at Umbraco.Core.Persistence.Database.OpenSharedConnection()
   at Umbraco.Core.Persistence.Database.<Query>d__7`1.MoveNext()
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey](IEnumerable`1 source, Func`2 keySelector)
   at Simple301.Core.RedirectRepository..cctor()
   --- End of inner exception stack trace ---
   at Simple301.Core.RedirectRepository.GetLookupTable()
   at Simple301.Core.RedirectContentFinder.TryFindContent(PublishedContentRequest request)
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at Umbraco.Web.Routing.PublishedContentRequestEngine.FindPublishedContent()
   at Umbraco.Web.Routing.PublishedContentRequestEngine.FindPublishedContentAndTemplate()
   at Umbraco.Web.Routing.PublishedContentRequestEngine.PrepareRequest()
   at Umbraco.Web.UmbracoModule.ProcessRequest(HttpContextBase httpContext)
   at System.Web.HttpApplication.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)

**Comment by wkallhof** [comment]
@tvanro 

In Simple301, there really isn't anything special in regard to database access. I created a new table within the existing CMS database and added check at application start of whether or not the table exists. If not, create it.

Based on the stack trace, it looks like Umbraco put in the request to the [Content Pipeline](https://our.umbraco.org/documentation/reference/routing/request-pipeline/) to find some piece of content within your site, and since the Simple301 [IContentFinder](https://our.umbraco.org/documentation/reference/routing/request-pipeline/icontentfinder) is set at the very beginning, it was the first to get that request. At that point, it appears that the plugin tried to connect to the database in order to check whether or not there was a redirect for the given request, and that is when the error occurs.

To me it looks like your application had issues connecting to your application database. The `Umbraco.Core.Persistence.Database.OpenSharedConnection()` along with an exception at `System.Data.ProviderBase.DbConnectionPool.TryGetConnection` appears to imply that Umbraco put out a request to get access to the database and that request failed. For whatever reason, your Web App and your database were not able to connect. If Simple301 wasn't there, the application would have still failed to run properly because Umbraco couldn't connect to its database.
